-- Migration number: 0001 	 2025-09-21T04:18:08.359Z
CREATE TABLE IF NOT EXISTS json_data (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  data TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);